/*
MIT License
Copyright (c) 2019 
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/
namespace ProfanityFilter
{
    /// <summary>
    /// This class contains the profanity list.
    ///
    /// WARNING : This file contains a lot of very offensive terminology. Do not read the content of this source code
    /// file if you are easily offended.
    /// </summary>
    public partial class ProfanityBase
    {
        private readonly string[] _wordList =
        {
             "2 girls 1 cup",
             "2 girls one cup",
             "2g1c",
             "4r5e",
             "5h1t",
             "5hit",
             "a$$hole",
             "a55hole",
             "anal",
             "anal impaler",
             "anal leakage",
             "analprobe",
             "anilingus",
             "angrydragon",
             "angry dragon",
             "anus",
             "apeshit",
             "ar5e",
             "arrse",
             "arse",
             "arses",
             "arsehole",
             "ass",
             "ass fuck",
             "ass hole",
             "assbag",
             "assbandit",
             "assbang",
             "assbanged",
             "assbanger",
             "assbangs",
             "assbite",
             "assclown",
             "asscock",
             "asscracker",
             "asses",
             "assface",
             "assfaces",
             "assfuck",
             "assfucker",
             "ass-fucker",
             "assfukka",
             "assgoblin",
             "assh0le",
             "asshat",
             "ass-hat",
             "asshead",
             "assho1e",
             "asshole",
             "assholes",
             "ass-jabber",
             "assjacker",
             "asslick",
             "asslicker",
             "assmaster",
             "assmonkey",
             "assmucus",
             "assmunch",
             "assmuncher",
             "assnigger",
             "asspirate",
             "ass-pirate",
             "assshit",
             "assshole",
             "asssucker",
             "asswad",
             "asswhole",
             "asswipe",
             "asswipes",
             "b!tch",
             "b17ch",
             "b1tch",
             "ball licking",
             "ball sack",
             "ball sucking",
             "ballsack",
             "bangbros",
             "bastard",
             "bastardo",
             "bastards",
             "bastinado",
             "batty boy",
             "bbw",
             "bdsm",
             "beaner",
             "beaners",
             "beardedclam",
             "beastial",
             "beastiality",
             "beatch",
             "beaver",
             "beaver cleaver",
             "beaver lips",
             "beef curtain",
             "beef curtains",
             "beeyotch",
             "bellend",
             "bender",
             "beotch",
             "bescumber",
             "bestial",
             "bestiality",
             "bi+ch",
             "biatch",
             "big breasts",
             "big knockers",
             "big tits",
             "bigtits",
             "bitch",
             "bitch tit",
             "bitchass",
             "bitched",
             "bitcher",
             "bitchers",
             "bitches",
             "bitchtits",
             "bitchy",
             "black cock",
             "bloodclaat",
             "blow job",
             "blow me",
             "blow mud",
             "blow your load",
             "blowjob",
             "blowjobs",
             "blue waffle",
             "blumpkin",
             "boiolas",
             "bollock",
             "bollocks",
             "bollok",
             "bollox",
             "bondage",
             "boned",
             "boner",
             "boners",
             "bong",
             "boong",
             "booobs",
             "boooobs",
             "booooobs",
             "booooooobs",
             "brotherfucker",
             "brown showers",
             "bukkake",
             "bull shit",
             "bulldyke",
             "bullet vibe",
             "bullshit",
             "bullshits",
             "bullshitted",
             "bullturds",
             "bum",
             "bum boy",
             "bumblefuck",
             "bumclat",
             "bummer",
             "bust a load",
             "butt fuck",
             "butt plug",
             "buttfuck",
             "buttfucka",
             "buttfucker",
             "butthole",
             "buttmuch",
             "buttmunch",
             "butt-pirate",
             "buttplug",
             "c.0.c.k",
             "c.o.c.k.",
             "c.u.n.t",
             "c0ck",
             "c-0-c-k",
             "c0cksucker",
             "caca",
             "cacafuego",
             "camel toe",
             "cameltoe",
             "camgirl",
             "camslut",
             "camwhore",
             "carpet muncher",
             "carpetmuncher",
             "chick with a dick",
             "child-fucker",
             "chinc",
             "chincs",
             "chink",
             "chinky",
             "choad",
             "choade",
             "chode",
             "chodes",
             "circlejerk",
             "cl1t",
             "clit",
             "clit licker",
             "clitface",
             "clitfuck",
             "clitoris",
             "clits",
             "clitty",
             "clitty litter",
             "clunge",
             "clusterfuck",
             "cnut",
             "cocain",
             "cocaine",
             "cock",
             "c-o-c-k",
             "cock pocket",
             "cock snot",
             "cock sucker",
             "cockass",
             "cockbite",
             "cockblock",
             "cockburger",
             "cockeye",
             "cockface",
             "cockfucker",
             "cockhead",
             "cockholster",
             "cockjockey",
             "cockknocker",
             "cockknoker",
             "cocklump",
             "cockmaster",
             "cockmongler",
             "cockmongruel",
             "cockmonkey",
             "cockmunch",
             "cockmuncher",
             "cocknose",
             "cocknugget",
             "cocks",
             "cockshit",
             "cocksmith",
             "cocksmoke",
             "cocksmoker",
             "cocksniffer",
             "cocksuck",
             "cocksucked",
             "cocksucker",
             "cock-sucker",
             "cocksuckers",
             "cocksucking",
             "cocksucks",
             "cocksuka",
             "cocksukka",
             "cockwaffle",
             "cokmuncher",
             "coksucka",
             "condom",
             "coochie",
             "coochy",
             "coon",
             "coonnass",
             "coons",
             "cooter",
             "coprolagnia",
             "coprophilia",
             "corksucker",
             "cornhole",
             "corp whore",
             "corpulent",
             "crackwhore",
             "creampie",
             "crotte",
             "cum",
             "cum chugger",
             "cum dumpster",
             "cum freak",
             "cum guzzler",
             "cumbubble",
             "cumdump",
             "cumdumpster",
             "cumguzzler",
             "cumjockey",
             "cummer",
             "cummin",
             "cumming",
             "cums",
             "cumshot",
             "cumshots",
             "cumslut",
             "cumstain",
             "cumtart",
             "cunnie",
             "cunnilingus",
             "cunny",
             "cunt",
             "c-u-n-t",
             "cunt hair",
             "cuntass",
             "cuntbag",
             "cuntface",
             "cunthole",
             "cunthunter",
             "cuntlick",
             "cuntlicker",
             "cuntrag",
             "cunts",
             "cuntsicle",
             "cuntslut",
             "cunt-struck",
             "cyalis",
             "cyberfuc",
             "cyberfuck",
             "cyberfucked",
             "cyberfucker",
             "cyberfucking",
             "d0ng",
             "d0uch3",
             "d0uche",
             "d1ck",
             "d1ld0",
             "d1ldo",
             "darkie",
             "darn",
             "date rape",
             "daterape",
             "deep throat",
             "deepthroat",
             "deggo",
             "dendrophilia",
             "dickbag",
             "dickbeaters",
             "dickdipper",
             "dickface",
             "dickflipper",
             "dickfuck",
             "dickfucker",
             "dickhead",
             "dickheads",
             "dickhole",
             "dickish",
             "dick-ish",
             "dickjuice",
             "dickmilk",
             "dickmonger",
             "dickripper",
             "dicks",
             "dicksipper",
             "dickslap",
             "dick-sneeze",
             "dicksucker",
             "dicksucking",
             "dicktickler",
             "dickwad",
             "dickweasel",
             "dickweed",
             "dickwhipper",
             "dickwod",
             "dickzipper",
             "diddle",
             "dike",
             "dildo",
             "dildos",
             "diligaf",
             "dillweed",
             "dog-fucker",
             "doublelift",
             "dp action",
             "dumbcunt",
             "dumbfuck",
             "dumbshit",
             "dumshit",
             "eat a dick",
             "eat hair pie",
             "eat my ass",
             "f u c k",
             "f u c k e r",
             "f.u.c.k",
             "f_u_c_k",
             "f4nny",
             "fagfucker",
             "fagg",
             "fagged",
             "fagging",
             "faggit",
             "faggitt",
             "faggot",
             "faggotcock",
             "faggots",
             "faggs",
             "fagot",
             "fagots",
             "fagtard",
             "fatass",
             "fcuk",
             "fcuker",
             "fcuking",
             "felch",
             "felcher",
             "felching",
             "fellate",
             "fellatio",
             "feltch",
             "feltcher",
             "female squirting",
             "fingerbang",
             "fingerfuck",
             "fingerfucked",
             "fingerfucker",
             "fingerfuckers",
             "fingerfucking",
             "fingerfucks",
             "fingering",
             "fist fuck",
             "fisted",
             "fistfuck",
             "fistfucked",
             "fistfucker",
             "fistfuckers",
             "fistfuckings",
             "fistfucks",
             "fisting",
             "fleshflute",
             "flog the log",
             "fook",
             "fooker",
             "footjob",
             "foreskin",
             "frotting",
             "fubar",
             "fuck",
             "f-u-c-k",
             "fuckyou",
             "fuck buttons",
             "fuck hole",
             "fuck off",
             "fuck puppet",
             "fuck trophy",
             "fuck yo mama",
             "fuck you",
             "fucka",
             "fuckass",
             "fuck-ass",
             "fuckbag",
             "fuck bag",
             "fuck-bitch",
             "fuckboy",
             "fuckbrain",
             "fuckbutt",
             "fuckbutter",
             "fucked",
             "fuckedup",
             "fucked up",
             "fucker",
             "fuckers",
             "fuckersucker",
             "fuckface",
             "fuckhead",
             "fuckheads",
             "fuckhole",
             "fuckin",
             "fucking",
             "fuckings",
             "fuckme",
             "fuck me",
             "fuckmeat",
             "fucknugget",
             "fucknut",
             "fucknutt",
             "fuckoff",
             "fucks",
             "fuckstick",
             "fucktard",
             "fuck-tard",
             "fucktards",
             "fucktart",
             "fucktoy",
             "fucktwat",
             "fuckup",
             "fuckwad",
             "fuckwhit",
             "fuckwit",
             "fuckwitt",
             "fudge packer",
             "fudgepacker",
             "fudge-packer",
             "fukwhit",
             "fukwit",
             "gang bang",
             "gangbang",
             "gang-bang",
             "gangbanged",
             "gangbangs",
             "gassy ass",
             "gay sex",
             "gayass",
             "gaybob",
             "gaydo",
             "gayfuck",
             "gayfuckist",
             "gaylord",
             "gays",
             "gaysex",
             "gaytard",
             "gaywad",
             "gender bender",
             "giant cock",
             "gippo",
             "glans",
             "goatcx",
             "goatse",
             "golden shower",
             "goldenshower",
             "golliwog",
             "gooch",
             "gook",
             "gooks",
             "goregasm",
             "gspot",
             "g-spot",
             "guro",
             "h0m0",
             "h0mo",
             "ham flap",
             "hand job",
             "handjob",
             "hardcoresex",
             "he-she",
             "holy shit",
             "homo",
             "homodumbshit",
             "homoerotic",
             "homoey",
             "hot carl",
             "hot chick",
             "hotsex",
             "iberian slap",
             "jackoff",
             "jack-off",
             "jagoff",
             "jap",
             "japs",
             "jelly donut",
             "jigaboo",
             "jiggaboo",
             "jiggerboo",
             "jism",
             "jiz",
             "jizm",
             "jizz",
             "jizzed",
             "jock",
             "juggs",
             "jungle bunny",
             "junglebunny",
             "junkie",
             "junky",
             "kafir",
             "kawk",
             "kike",
             "kikes",
             "kinbaku",
             "kinkster",
             "kinky",
             "klan",
             "knobjocky",
             "knobjokey",
             "kock",
             "kondum",
             "kondums",
             "kooch",
             "kooches",
             "kootch",
             "kyke",
             "lameass",
             "lardass",
             "male squirting",
             "masterb8",
             "masterbat*",
             "masterbat3",
             "masterbate",
             "master-bate",
             "masterbating",
             "masterbation",
             "masterbations",
             "masturbate",
             "masturbating",
             "masturbation",
             "mcfagget",
             "menage a trois",
             "m-fucking",
             "mick",
             "microphallus",
             "milf",
             "minge",
             "minger",
             "mong",
             "moo moo foo foo",
             "moolie",
             "moron",
             "mothafuck",
             "mothafucka",
             "mothafuckas",
             "mothafuckaz",
             "mothafucked",
             "mothafucker",
             "mothafuckers",
             "mothafuckin",
             "mothafucking",
             "mothafuckings",
             "mothafucks",
             "mother fucker",
             "motherfuck",
             "motherfucka",
             "motherfucked",
             "motherfucker",
             "motherfuckers",
             "motherfuckin",
             "motherfucking",
             "motherfuckings",
             "motherfuckka",
             "motherfucks",
             "muff",
             "muff diver",
             "muff puff",
             "muffdiver",
             "muffdiving",
             "munging",
             "munter",
             "murder",
             "mutha",
             "muthafecker",
             "muthafuckker",
             "muther",
             "mutherfucker",
             "n1gga",
             "n1gger",
             "nappy",
             "nawashi",
             "need the dick",
             "negro",
             "nig nog",
             "nigaboo",
             "nigg3r",
             "nigg4h",
             "nigga",
             "niggah",
             "niggas",
             "niggaz",
             "nigger",
             "niggers",
             "niggle",
             "niglet",
             "nig-nog",
             "nimphomania",
             "ninny",
             "ninnyhammer",
             "nipple",
             "nipples",
             "nob jokey",
             "nobhead",
             "nobjocky",
             "nobjokey",
             "nonce",
             "nsfw images",
             "nutsack",
             "nutter",
             "one cup two girls",
             "1 cup 2 girls",
             "one cup 2 girls",
             "1 cup two girls",
             "one guy one jar",
             "1 guy one jar",
             "one guy 1 jar",
             "p.u.s.s.y.",
             "p.u.s.s.y",
             "p0rn",
             "paedophile",
             "paki",
             "panooch",
             "pecker",
             "peckerhead",
             "pedo",
             "pedobear",
             "pedophile",
             "pedophilia",
             "pedophiliac",
             "penisbanger",
             "penisfucker",
             "penispuffer",
             "phone sex",
             "phonesex",
             "phuck",
             "phuk",
             "phuked",
             "phuking",
             "phukked",
             "phukking",
             "phuks",
             "phuq",
             "piece of shit",
             "pigfucker",
             "pikey",
             "pillowbiter",
             "pimp",
             "pimpis",
             "pinko",
             "piss",
             "piss off",
             "piss pig",
             "pissed off",
             "pisser",
             "pissers",
             "pisses",
             "pissflaps",
             "piss flaps",
             "pissin",
             "pissing",
             "pissoff",
             "piss-off",
             "pisspig",
             "polack",
             "pole smoker",
             "polesmoker",
             "ponyplay",
             "poon",
             "poonani",
             "poonany",
             "poontang",
             "poop chute",
             "poopchute",
             "Poopuncher",
             "porch monkey",
             "porchmonkey",
             "porn",
             "porno",
             "pornography",
             "pornos",
             "potty",
             "prick",
             "pricks",
             "prickteaser",
             "prig",
             "pron",
             "prone bone",
             "pronebone",
             "prone-bone",
             "pthc",
             "pubic",
             "pubis",
             "punani",
             "punanny",
             "punany",
             "punkass",
             "punta",
             "puss",
             "pusse",
             "pussi",
             "pussies",
             "pussy",
             "pussy fart",
             "pussy palace",
             "pussylicking",
             "pussypounder",
             "pussys",
             "pust",
             "puto",
             "queaf",
             "queef",
             "queer",
             "queerbait",
             "queerhole",
             "queero",
             "queers",
             "quicky",
             "quim",
             "racy",
             "raghead",
             "raging boner",
             "rape",
             "raped",
             "raper",
             "rapey",
             "raping",
             "rapist",
             "rectus",
             "reefer",
             "reetard",
             "reich",
             "renob",
             "retard",
             "retarded",
             "rimjaw",
             "rimjob",
             "rimming",
             "ritard",
             "rosy palm",
             "rosy palm and her 5 sisters",
             "rtard",
             "r-tard",
             "rump",
             "rumprammer",
             "ruski",
             "rusty trombone",
             "s&m",
             "s.h.i.t.",
             "s_h_i_t",
             "s0b",
             "sambo",
             "sand nigger",
             "sandbar",
             "Sandler",
             "sandnigger",
             "sausage queen",
             "scag",
             "scantily",
             "scat",
             "schizo",
             "schlong",
             "scroat",
             "scrog",
             "scrot",
             "scrote",
             "scrotum",
             "scrud",
             "scum",
             "seks",
             "sh!+",
             "sh!t",
             "sh1t",
             "s-h-1-t",
             "shag",
             "shagger",
             "shaggin",
             "shagging",
             "shamedame",
             "shaved beaver",
             "shaved pussy",
             "shemale",
             "shi+",
             "shibari",
             "shirt lifter",
             "shit",
             "s-h-i-t",
             "shit ass",
             "shit fucker",
             "shitass",
             "shitbag",
             "shitbagger",
             "shitblimp",
             "shitbrains",
             "shitbreath",
             "shitcanned",
             "shitcunt",
             "shitdick",
             "shite",
             "shiteater",
             "shited",
             "shitey",
             "shitface",
             "shitfaced",
             "shitfuck",
             "shitfull",
             "shithead",
             "shitheads",
             "shithole",
             "shithouse",
             "shiting",
             "shitings",
             "shits",
             "shitspitter",
             "shitstain",
             "shitt",
             "shitted",
             "shitter",
             "shitters",
             "shittier",
             "shittiest",
             "shitting",
             "shittings",
             "shitty",
             "shiz",
             "shiznit",
             "shota",
             "shrimping",
             "sissy",
             "skag",
             "skank",
             "skeet",
             "skullfuck",
             "slanteye",
             "slut",
             "slut bucket",
             "slutbag",
             "slutdumper",
             "slutkiss",
             "sluts",
             "smartass",
             "smartasses",
             "smeg",
             "smegma",
             "smut",
             "smutty",
             "snatch",
             "s-o-b",
             "sod off",
             "sodom",
             "sodomize",
             "sodomy",
             "son of a bitch",
             "son of a motherless goat",
             "son of a whore",
             "son-of-a-bitch",
             "souse",
             "soused",
             "spac",
             "spade",
             "sperm",
             "spic",
             "spick",
             "spik",
             "spiks",
             "splooge",
             "splooge moose",
             "spooge",
             "spook",
             "spread legs",
             "spunk",
             "stfu",
             "stiffy",
             "suckass",
             "sultry women",
             "t1tt1e5",
             "t1tties",
             "taff",
             "taig",
             "tard",
             "tart",
             "taste my",
             "tawdry",
             "tea bagging",
             "teabagging",
             "throating",
             "thundercunt",
             "thunder cunt",
             "tit",
             "tit wank",
             "titfuck",
             "titi",
             "tities",
             "tits",
             "titt",
             "tittie5",
             "tittiefucker",
             "titties",
             "titty",
             "tittyfuck",
             "tittyfucker",
             "tittywank",
             "titwank",
             "toke",
             "toots",
             "topless",
             "tosser",
             "towelhead",
             "tub girl",
             "tubgirl",
             "twat",
             "twathead",
             "twatlips",
             "twats",
             "twatty",
             "twatting",
             "twatwaffle",
             "twink",
             "two fingers with tongue",
             "two girls 1 cup",
             "two girls one cup",
             "twunt",
             "twunter",
             "unclefucker",
             "urethra play",
             "urinal",
             "urine",
             "urophilia",
             "uterus",
             "vajayjay",
             "va-j-j",
             "valium",
             "venus mound",
             "veqtable",
             "violet wand",
             "vjayjay",
             "vodka",
             "vorarephilia",
             "w00se",
             "wad",
             "wang",
             "wank",
             "wanker",
             "wankjob",
             "wanky",
             "wazoo",
             "weenie",
             "weewee",
             "weiner",
             "weirdo",
             "wench",
             "wet dream",
             "wetback",
             "white power",
             "whiz",
             "whoar",
             "whoralicious",
             "whore",
             "whorealicious",
             "whorebag",
             "whored",
             "whoreface",
             "whorehopper",
             "whorehouse",
             "whores",
             "whoring",
             "wigger",
             "window licker",
             "wiseass",
             "wiseasses",
             "wog",
             "womb",
             "wop",
             "yaoi",
             "yeasty",
             "yellow showers",
             "yid",
             "yiffy",
             "zibbi",
             "zubb",
        };
    }
}
